development:
  adapter: postgresql
  database: kanban_dev
  username: postgres
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: kanban_test
  username: postgres
  host: localhost
  pool: 5
  timeout: 5000
